= Tiny BASIC Compiler

TBC is a compiler for the Tiny BASIC programming language, common on older microcomputers due to the original interpreter's tiny size (3K).
I programmed this as a self-tutorial on how to write compilers and as a basis for a future BASIC compiler I plan on writing for the Arduino microcontroller.
There are certain areas where TBC strays from the canonical Tiny BASIC implementation, however, mainly derived from the compiler's esoteric basis and certain practical limitations.

== Limitations

* You cannot place arbitrary spaces in keywords. `GO TO <> GOTO`.
* You cannot jump to calculated positions; `GOTO` only accepts plain integers.
* The `CLEAR` and `LIST` directives are not implemented because they have no place in this type of compiler.

== Platforms

The primary target of TBC is Netwide Assembler that can be compiled into MS-DOS, FreeDOS or DosBox COM executables.
Support for other platforms may come in the future.

TBC is written in forwards-compatible K&R C using only the `getopt` extension.
It should be compilable with the vast majority of C and C++ compilers.
We provide a copy of BSD's `getopt` implementation (`getopt.c`) for situations where a native version is not available.
For more information, see <<Installation>>.

== Installation

No build scripts are provided because, in my opinion, TBC is simple enough to lack them.
On most systems you will probably use the GNU Compiler Collection, with the exception of Windows where there's a high chance you will want to use the Microsoft Visual C++ Compiler.

TBC has been written in forwards-compatible K&R C which means that it can be compiled with Bruce's C Compiler for embedded Linux systems if you wanted that (unlikely).
For compilers that lack an implementation of `getopt` (i.e. MSVC), you will have to include `getopt.c` in the list of source files.

With the GNU Compiler Collection,

        gcc tbc.c -o tbc

With the Microsoft Visual C++ Compiler,

        cl tbc.c getopt.c

With Bruce's C Compiler,

        bcc tbc.c -o tbc

To target i386 Linux or MS-DOS pass `-Mg` and `-Md` to Bruce, respectively.
The majority of alternative compilers should function in a similar fashion.
Actual installation is as simple as putting the resulting executable (`tbc` or `tbc.exe`) somewhere in your system's program search path.

== Syntax Highlighting

I provide a GtkSourceView-3.0 script for GEdit in `tinybasic.lang`.
Copy this into `/usr/share/gtksourceview-3.0/language-specs` and restart GEdit to start highlighting `.bas` files in TinyBASIC.
`/usr/local/share` and `/home/you/.local/share` are valid alternatives to `/usr/share` in most configurations.

As far as I can tell, ViM already supports TinyBASIC syntax.
Feel free to send me syntax definitions for other text editors and I might include them with the compiler (with appropriate credit, of course).

== Copyright and License

Copyright (C) 2012 Megan Ruggiero. All rights reserved.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
